version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: teamseas-api-db
    environment:
      MYSQL_DATABASE: teamseas-api
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
